//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalSalones
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DS2_ProyectoFinalSalonesDBEntities : DbContext
    {
        public DS2_ProyectoFinalSalonesDBEntities()
            : base("name=DS2_ProyectoFinalSalonesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Propietario> Propietarios { get; set; }
        public virtual DbSet<Salone> Salones { get; set; }
        public virtual DbSet<Tipo> Tipoes { get; set; }
    }
}
