//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalSalones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salone
    {
        public string Id { get; set; }
        public string Nombre { get; set; }
        public int Superficie { get; set; }
        public string Direccion { get; set; }
        public decimal Precio { get; set; }
        public string Tipo_Id { get; set; }
        public bool Disponibilidad { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public string Propietario_Id { get; set; }
        public Nullable<System.DateTime> InicioAlquilerActual { get; set; }
        public Nullable<System.DateTime> FinAlquilerActual { get; set; }
        public string Cliente_Id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Propietario Propietario { get; set; }
    }
}
