//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalSalones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccione
    {
        public string Id { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Cliente_Id { get; set; }
        public string Salon_Id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Salone Salone { get; set; }
    }
}
